// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPnBdIbKNXs29BYAqVN4Qrsr-41pT1dQo',
    appId: '1:62699433595:android:0b44089acafd4cb6b43cde',
    messagingSenderId: '62699433595',
    projectId: 'instagram-clone-1fcda',
    storageBucket: 'instagram-clone-1fcda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfMQOZBX-fIj9fsgpOD5fK1ORpkIgZvB8',
    appId: '1:62699433595:ios:68ee0b59e73bd690b43cde',
    messagingSenderId: '62699433595',
    projectId: 'instagram-clone-1fcda',
    storageBucket: 'instagram-clone-1fcda.appspot.com',
    iosBundleId: 'com.example.instagramCloneTutorial',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa1ccg5o752OF4o2T_7CI_50T0CGxkZP4',
    appId: '1:62699433595:web:1477803b3031300fb43cde',
    messagingSenderId: '62699433595',
    projectId: 'instagram-clone-1fcda',
    authDomain: 'instagram-clone-1fcda.firebaseapp.com',
    storageBucket: 'instagram-clone-1fcda.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfMQOZBX-fIj9fsgpOD5fK1ORpkIgZvB8',
    appId: '1:62699433595:ios:68ee0b59e73bd690b43cde',
    messagingSenderId: '62699433595',
    projectId: 'instagram-clone-1fcda',
    storageBucket: 'instagram-clone-1fcda.appspot.com',
    iosBundleId: 'com.example.instagramCloneTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa1ccg5o752OF4o2T_7CI_50T0CGxkZP4',
    appId: '1:62699433595:web:03ee6215c8437852b43cde',
    messagingSenderId: '62699433595',
    projectId: 'instagram-clone-1fcda',
    authDomain: 'instagram-clone-1fcda.firebaseapp.com',
    storageBucket: 'instagram-clone-1fcda.appspot.com',
  );

}